### ISSUE TITLE
On macOS dlopen of libarchive fails with "image not found"

### ISSUE THREAD

**Issue by saraedum** [conda-forge/python-libarchive-c-feedstock#6]
I am having trouble with an automated build for macOS on CircleCI at https://github.com/conda-forge/sagelib-feedstock/pull/52.

```
+ set -e
+ conda build ./recipe -m ./.ci_support/osx_python2.7.yaml
+ '[' 4 -lt 1 ']'
+ local cmd=build
+ shift
+ case "$cmd" in
+ /Users/distiller/miniconda3/bin/conda build ./recipe -m ./.ci_support/osx_python2.7.yaml
Traceback (most recent call last):
  File "/Users/distiller/miniconda3/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 10, in <module>
    import libarchive
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/distiller/miniconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/Users/distiller/miniconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/Users/distiller/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/distiller/miniconda3/lib/libarchive, 6): image not found
Exited with code 1
```
Essentially the same happens with the Python 3.6 build. However the builds work fine on Linux.

The full log is here: https://circleci.com/gh/conda-forge/sagelib-feedstock/386?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I do not understand what is going on here so I might be doing something obvious wrong.

**Comment by mingwandroid** [comment]
On AD we're having some trouble on Linux with this:

https://github.com/ContinuumIO/docker-images/issues/95

**Comment by mingwandroid** [comment]
I'm trying to get to the bottom of it ASAP.

**Comment by rainwoodman** [comment]
Thanks. We just got hit by this in a PR on https://github.com/conda-forge/cfitsio-feedstock/pull/14 .

**Comment by mingwandroid** [comment]
Workaround:

`apt-get install binutils`

Seems `libarchive` depends upon this to find symbols in the dynamic library. I don't know why it doesn't just try to find them with ctypes instead. Looking into amending that now.

**Comment by rainwoodman** [comment]
It appears to be using ctypes -- see the stack trace. Perhaps binutils adds additional search paths to _dlopen() ?

**Comment by mingwandroid** [comment]
No, it's worse than this, python itself uses objdump, I am flabbergasted.

```
grep -R objdump /opt/conda/pkgs/python-3.6.6-hc3d631a_0
Binary file /opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/__pycache__/util.cpython-36.pyc matches
/opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/util.py:    # Andreas Degert's find functions, using gcc, /sbin/ldconfig, objdump
/opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/util.py:            objdump = shutil.which('objdump')
/opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/util.py:            if not objdump:
/opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/util.py:                # objdump is not available, give up
/opt/conda/pkgs/python-3.6.6-hc3d631a_0/lib/python3.6/ctypes/util.py:                proc = subprocess.Popen((objdump, '-p', '-j', '.dynamic', f),
```

**Comment by mingwandroid** [comment]
AFAICT, all these failures are due to `binutils` not being found on `PATH`, I do not think it has anything to do with search paths to `_dlopen()`. It fails in `_get_soname()` which tries to use `objdump`.

**Comment by rainwoodman** [comment]
On OSX find_library appears to use 'framework' stuff instead of objdump:

From here:

https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/ctypes/util.py#L70

**Comment by mingwandroid** [comment]
Not *really*, it looks in system paths first.

https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/ctypes/util.py#L73-L75 AFAIR, frameworks come last.

We modified this code though so that it also looks in sysprefix/lib, but that's not related to this issue, that bit's working fine.

**Comment by mingwandroid** [comment]
OK yeah, on mac it isn't calling `objdump` which makes it even trickier for me to figure out what's up with this one. I've made some progress on linux with having a fallback for `objdump` but it's not finished yet.

Reproduction steps that do not involve CI for this macOS thing would be appreciated if anyone can figure them out.

**Comment by mingwandroid** [comment]
@rainwoodman, can you change:

```
conda build ./recipe -m ./.ci_support/${CONFIG}.yaml
```

.. over at https://travis-ci.org/conda-forge/cfitsio-feedstock/builds/438897480?utm_source=github_status&utm_medium=notification to:

```
DYLD_PRINT_LIBRARIES=1 conda build ./recipe -m ./.ci_support/${CONFIG}.yaml
```

and show me the results?

**Comment by mingwandroid** [comment]
Actually don't worry, I know what's wrong:

This works fine on defaults. It's broken here due to https://github.com/conda-forge/python-libarchive-c-feedstock/blob/master/recipe/scripts/activate.sh#L10

```
export LIBARCHIVE=$CONDA_PREFIX/lib/libarchive${SHLIB_EXT}
```

`SHLIB_EXT` is nothing at the point that's executed so it tries to load `$CONDA_PREFIX/lib/libarchive` which is consistent with the stack trace.

I noticed that the CF `libarchive` package supports a lot less formats than the one on defaults. You probably want to enable a few more. From the AD `.pc` file:

```
Libs.private: -llzo2 -llzma -lzstd -llz4 -lcharset -lbz2 -lz  -L/opt/anaconda1anaconda2anaconda3/lib -lxml2
```

.. from the CF `.pc` file:

```
Libs.private: -lexpat -llzma -lcharset -lbz2 -lz 
```

**Comment by rainwoodman** [comment]
Thanks!
